---
name: Segunda Práctica Objetos y Colecciones
locale: es
type: practice
beta: false
teacher_info: Basado en https://docs.google.com/document/d/1Thx-haRfLg-3b_69YlGeJ0E6zOoSTVHg_bgmo4YjK5c/edit#
language: wollok
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
